# Generated by Django 6.0.6 on 2026-06-15 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='اسم الكورس')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('cover_image', models.ImageField(upload_to='courses/covers/', verbose_name='صورة الغلاف')),
                ('short_description', models.TextField(verbose_name='وصف مختصر')),
                ('full_description', models.TextField(verbose_name='وصف كامل')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration', models.CharField(max_length=100, verbose_name='مدة الكورس')),
                ('lesson_count', models.PositiveIntegerField(default=0, verbose_name='عدد الدروس')),
                ('skills', models.TextField(help_text='افصل بين المهارات بفاصلة', verbose_name='المهارات')),
                ('projects', models.TextField(help_text='افصل بين المشاريع بفاصلة', verbose_name='المشاريع')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': 'الكورسات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('student_title', models.CharField(blank=True, max_length=255, verbose_name='المسمى')),
                ('content', models.TextField(verbose_name='الرأي')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='التقييم')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رأي طالب',
                'verbose_name_plural': 'آراء الطلاب',
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الأسبوع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'verbose_name': 'أسبوع',
                'verbose_name_plural': 'الأسابيع',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مفعّل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الدرس')),
                ('lesson_type', models.CharField(choices=[('video', 'فيديو'), ('pdf', 'PDF'), ('assignment', 'واجب'), ('file', 'ملف')], default='video', max_length=20, verbose_name='نوع الدرس')),
                ('video', models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='فيديو')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط فيديو خارجي')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدرس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursesection')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file', models.FileField(upload_to='courses/files/', verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('other', 'ملف إضافي')], default='pdf', max_length=10, verbose_name='نوع الملف')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'ملف درس',
                'verbose_name_plural': 'ملفات الدروس',
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('proof_image', models.ImageField(upload_to='payments/', verbose_name='إثبات الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='courses.coursesubscription')),
            ],
            options={
                'verbose_name': 'إثبات دفع',
                'verbose_name_plural': 'إثباتات الدفع',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='ملف الشهادة')),
                ('completion_date', models.DateField(verbose_name='تاريخ الإكمال')),
                ('instructor_name', models.CharField(default='ماركو زكريا', max_length=255, verbose_name='اسم المدرب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
